<template>
  <div>
    <h1
      text-2xl
      font-bold
      mb-6
    >
      Login
    </h1>
    <form
      space-y-4
    >
      <div>
        <label
          block
          mb-1
        >Email</label>
        <input
          type="email"
          required
          w-full
          px-4
          py-2
          border
          rounded
        >
      </div>
      <div>
        <label
          block
          mb-1
        >Password</label>
        <input
          type="password"
          required
          w-full
          px-4
          py-2
          border
          rounded
        >
      </div>
      <div>
        <button
          type="submit"
          w-full
          px-4
          py-2
          bg-green-500
          rounded
        >
          Login
        </button>
      </div>
    </form>
  </div>
</template>
