version: "3.9"
services:
  node20-supabase:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
    stdin_open: true
    working_dir: "/workspace"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
